name: Build and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: "10.4.1"

      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: |
          pnpm run lint
          pnpm run build

          cp dist/planb.js examples/planb.js

      - name: Upload to Github Page
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
